name: hotkdump # you probably want to 'snapcraft register <name>'
base: core22 # the base snap is the execution environment for this snap
version: '2024.7.1' # just for humans, typically '1.2+git' or '1.3.2'
summary: Easily open and analyze linux kernel crash dumps. # 79 char long summary
description: |
  hotkdump allows automatic analysis of Linux kernel crash dumps generated
  with `kdump`. It also acts as a crash launcher by automatically downloading
  the required `.ddeb` file for the crash file's kernel version, making it easier
  for end user to open the kernel dumps.

  hotkdump has an bundled version of `crash` available inside the package, and will
  use that by default. It can also use the user-specified `crash` when needed.
issues: https://github.com/canonical/hotkdump/issues
license: GPL-3.0
source-code: https://github.com/canonical/hotkdump
website: https://github.com/canonical/hotkdump
icon: extras/img/hotkdump-logo.png
# ubuntutools uses APT python API to initialize the .deb package
# and `apt_pkg.init()` needs these path/files to be present, so
# we're pointing them to the right ones.
layout:
  /etc/apt/apt.conf.d:
    bind: $SNAP_DATA/etc/apt/apt.conf.d
  /usr/share/dpkg/cputable:
    bind-file: $SNAP/usr/share/dpkg/cputable
  /usr/share/dpkg/tupletable:
    bind-file: $SNAP/usr/share/dpkg/tupletable
  /etc/dpkg:
    bind: $SNAP/etc/dpkg
grade: stable # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
apps:
  hotkdump:
    command: bin/hotkdump
    environment:
      PYTHONPATH: $SNAP/usr/lib/python3/site-packages:$SNAP/usr/lib/python3/dist-packages:$PYTHONPATH
      # Set the auto extension load path for crash
      CRASH_EXTENSIONS: $SNAP/usr/lib64/crash/extensions/
    plugs:
      - home
      - network
      - network-bind
parts:
  crash:
    source: https://github.com/crash-utility/crash/archive/refs/tags/8.0.5.tar.gz
    plugin: make
    build-packages:
      # The list of packages needed to build `crash`
      - g++
      - wget
      - make
      - libcurses-ocaml-dev
      - zlib1g-dev
      - bison
      - texinfo
      - python3
  hotkdump:
    plugin: python
    source: .
    after: [pykdump]
    build-packages:
      - python3-pip
    stage-packages:
      # Needed for hotkdump
      - ubuntu-dev-tools
      - dpkg # needed by ubuntu-dev-tools
      - debuginfod
  pykdump:
    plugin: make
    after: [crash]
    source: git://git.code.sf.net/p/pykdump/code
    override-build: |
      # Adapted from official instructions: https://pykdump.readthedocs.io/en/latest/install/build-steps.html 
      # Build python from source. We're using Python 3.8 right now because
      # Python 3.10 isn't working for pykdump.
      wget https://www.python.org/ftp/python/3.8.19/Python-3.8.19.tgz
      tar -xvzf Python-3.8.19.tgz
      cd $CRAFT_PART_BUILD/Python-3.8.19
      # Configure Python to produce position-independent static library
      ./configure CFLAGS=-fPIC --disable-shared
      # Fetch the modified setup.local file from pykdump repository, and override the existing one for Python
      wget https://sourceforge.net/p/pykdump/code/ci/master/tree/Extension/Setup.local-3.8?format=raw -O Modules/Setup.local
      # Compile Python
      make -j32
      # Go into pykdump/Extension folder
      cd $CRAFT_PART_BUILD/Extension
      # Point to the python and crash folders
      ./configure -p $CRAFT_PART_BUILD/Python-3.8.19 -c $SNAPCRAFT_STAGE/../parts/crash/build
      # Build the pykdump crash extension
      make
      # Create target directory for install
      mkdir -p $CRAFT_PART_INSTALL/usr/lib64/crash/extensions
      # Modify the make install target. By default, the target path is ~/.crash.d/
      sed -i 's|$$HOME/\.crash\.d|'$CRAFT_PART_INSTALL'/usr/lib64/crash/extensions|g' Makefile
      make install
    # We only need mpykdump.so from all of this.
    stage:
      - usr/lib64/crash/extensions/mpykdump.so
    prime:
      - usr/lib64/crash/extensions/mpykdump.so
    build-packages:
      - build-essential
      - libffi-dev
      - libreadline-dev
      - zip
      - texinfo
